"""Correlation keys and sync-job persistence.

Adds the identifiers that make cross-system correlation possible, and a table
recording what each ingestion run actually did.

Until now no table stored a commit SHA, so there was no key on which any two
systems could be joined — which is why delivery traces, bottlenecks and conflict
detection could not be built. ``merge_commit_sha`` in particular is the commit
that lands on the base branch, and therefore the one a later build or deployment
reports having shipped.

All new columns are nullable. Rows ingested before this migration have no SHA,
and back-filling them requires re-syncing from the provider rather than
inventing a value.

Revision ID: 0002_correlation
Revises: 0001_baseline
Create Date: 2026-09-10 10:32:16.541397
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002_correlation'
down_revision: Union[str, None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('pull_requests_written', sa.Integer(), nullable=False),
    sa.Column('workflow_runs_written', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_jobs_id'), 'sync_jobs', ['id'], unique=False)
    op.add_column('pull_requests', sa.Column('head_sha', sa.String(), nullable=True))
    op.add_column('pull_requests', sa.Column('merge_commit_sha', sa.String(), nullable=True))
    op.add_column('pull_requests', sa.Column('base_branch', sa.String(), nullable=True))
    op.add_column('pull_requests', sa.Column('head_branch', sa.String(), nullable=True))
    op.add_column('pull_requests', sa.Column('author_login', sa.String(), nullable=True))
    op.add_column('pull_requests', sa.Column('closed_at', sa.DateTime(), nullable=True))
    op.add_column('pull_requests', sa.Column('html_url', sa.String(), nullable=True))
    op.create_index('ix_pull_requests_head_sha', 'pull_requests', ['head_sha'], unique=False)
    op.create_index('ix_pull_requests_merge_commit_sha', 'pull_requests', ['merge_commit_sha'], unique=False)
    # The MVP upserted pull requests with a read-then-write and no constraint, so
    # a database written by concurrent syncs may already contain duplicates.
    # Adding the constraint would abort on those rows, so collapse them first,
    # keeping the lowest id of each group as the surviving row.
    op.execute(
        """
        DELETE FROM pull_requests a
        USING pull_requests b
        WHERE a.repository_id = b.repository_id
          AND a.github_pr_number = b.github_pr_number
          AND a.id > b.id
        """
    )
    op.create_unique_constraint('uq_pull_request_number', 'pull_requests', ['repository_id', 'github_pr_number'])
    op.add_column('workflow_runs', sa.Column('head_sha', sa.String(), nullable=True))
    op.add_column('workflow_runs', sa.Column('head_branch', sa.String(), nullable=True))
    op.add_column('workflow_runs', sa.Column('event', sa.String(), nullable=True))
    op.add_column('workflow_runs', sa.Column('status', sa.String(), nullable=True))
    op.add_column('workflow_runs', sa.Column('run_attempt', sa.Integer(), nullable=True))
    op.add_column('workflow_runs', sa.Column('html_url', sa.String(), nullable=True))
    op.create_index('ix_workflow_runs_head_sha', 'workflow_runs', ['head_sha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_runs_head_sha', table_name='workflow_runs')
    op.drop_column('workflow_runs', 'html_url')
    op.drop_column('workflow_runs', 'run_attempt')
    op.drop_column('workflow_runs', 'status')
    op.drop_column('workflow_runs', 'event')
    op.drop_column('workflow_runs', 'head_branch')
    op.drop_column('workflow_runs', 'head_sha')
    op.drop_constraint('uq_pull_request_number', 'pull_requests', type_='unique')
    op.drop_index('ix_pull_requests_merge_commit_sha', table_name='pull_requests')
    op.drop_index('ix_pull_requests_head_sha', table_name='pull_requests')
    op.drop_column('pull_requests', 'html_url')
    op.drop_column('pull_requests', 'closed_at')
    op.drop_column('pull_requests', 'author_login')
    op.drop_column('pull_requests', 'head_branch')
    op.drop_column('pull_requests', 'base_branch')
    op.drop_column('pull_requests', 'merge_commit_sha')
    op.drop_column('pull_requests', 'head_sha')
    op.drop_index(op.f('ix_sync_jobs_id'), table_name='sync_jobs')
    op.drop_table('sync_jobs')
    # ### end Alembic commands ###
