"""deployment model

Revision ID: 0003_deployments
Revises: 0002_correlation
Create Date: 2026-09-10 10:57:57.219929
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003_deployments'
down_revision: Union[str, None] = '0002_correlation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('workflow_name_pattern', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('is_production', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'workflow_name_pattern', 'environment', name='uq_deployment_rule')
    )
    op.create_index(op.f('ix_deployment_rules_id'), 'deployment_rules', ['id'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('is_production', sa.Boolean(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'provider', 'external_id', name='uq_deployment_external')
    )
    op.create_index('ix_deployments_commit_sha', 'deployments', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_deployments_id'), 'deployments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployments_id'), table_name='deployments')
    op.drop_index('ix_deployments_commit_sha', table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_deployment_rules_id'), table_name='deployment_rules')
    op.drop_table('deployment_rules')
    # ### end Alembic commands ###
