"""rca analyses

Revision ID: 0005_rca
Revises: 0004_runtime
Create Date: 2026-09-10 11:54:27.407349
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0005_rca'
down_revision: Union[str, None] = '0004_runtime'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rca_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=True),
    sa.Column('evidence_hash', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rca_analyses_evidence_hash', 'rca_analyses', ['evidence_hash'], unique=False)
    op.create_index(op.f('ix_rca_analyses_id'), 'rca_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rca_analyses_id'), table_name='rca_analyses')
    op.drop_index('ix_rca_analyses_evidence_hash', table_name='rca_analyses')
    op.drop_table('rca_analyses')
    # ### end Alembic commands ###
