"""anomalies

Revision ID: 0006_anomalies
Revises: 0005_rca
Create Date: 2026-09-11 22:20:38.856555
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0006_anomalies'
down_revision: Union[str, None] = '0005_rca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=False),
    sa.Column('change_pct', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('baseline_sample_count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'metric', 'window_start', name='uq_anomaly_window')
    )
    op.create_index('ix_anomalies_detected_at', 'anomalies', ['detected_at'], unique=False)
    op.create_index(op.f('ix_anomalies_id'), 'anomalies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomalies_id'), table_name='anomalies')
    op.drop_index('ix_anomalies_detected_at', table_name='anomalies')
    op.drop_table('anomalies')
    # ### end Alembic commands ###
